//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasMF.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int Capacidad { get; set; }
        public int NumeroHabitacion { get; set; }
        public bool Disponible { get; set; }
    }
}
